language: node_js
node_js:
  - '12'
services:
  - docker

before_install:
  - npm install

script:
  - npm run docs:build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t zhaojixiang1/zjx-ui:latest .
  - docker push zhaojixiang1/zjx-ui:latest
